/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginandsignup;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sauls
 */
public class AgreViaje extends javax.swing.JFrame {

    /**
     * Creates new form AgreViaje
     */
    public AgreViaje() {
        initComponents();
        agregarViaje();
        limpiarCampos();
    }

                                         
    private void agregarViaje(){
    try {
        // Convertimos los campos a enteros
        int lunes     = Integer.parseInt(jlun.getText().trim());
        int martes    = Integer.parseInt(jmar.getText().trim());
        int miercoles = Integer.parseInt(jmier.getText().trim());
        int jueves    = Integer.parseInt(jjue.getText().trim());
        int viernes   = Integer.parseInt(jvier.getText().trim());
        int sabado    = Integer.parseInt(jsab.getText().trim());
        int domingo   = Integer.parseInt(jdom.getText().trim());

        String url = "jdbc:mysql://localhost:3307/registro";
        String usr = "root";
        String pwd = "";
        String sql = "INSERT INTO viaje (lunes, martes, miercoles, jueves, viernes, sabado, domingo) VALUES (?, ?, ?, ?, ?, ?, ?)";

        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection(url, usr, pwd);
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, lunes);
            ps.setInt(2, martes);
            ps.setInt(3, miercoles);
            ps.setInt(4, jueves);
            ps.setInt(5, viernes);
            ps.setInt(6, sabado);
            ps.setInt(7, domingo);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Viaje registrado correctamente.");
            limpiarCampos(); // recarga la tabla
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Todos los campos deben ser números enteros.\nVerifica que no haya campos vacíos o letras.",
            "Error de entrada", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error al registrar el viaje:\n" + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    } 

    }  

private void limpiarCampos() {
    jlun.setText("");
    jmar.setText("");
    jmier.setText("");
    jjue.setText("");
    jvier.setText("");
    jsab.setText("");
    jdom.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel113 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jlun = new javax.swing.JTextField();
        jmar = new javax.swing.JTextField();
        jmier = new javax.swing.JTextField();
        jjue = new javax.swing.JTextField();
        jvier = new javax.swing.JTextField();
        jsab = new javax.swing.JTextField();
        jdom = new javax.swing.JTextField();
        jButton133 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();

        jLabel113.setText("Agregar Viaje ");

        jLabel22.setText("Lunes");

        jLabel32.setText("Martes");

        jLabel42.setText("Miercoles");

        jLabel52.setText("Jueves");

        jLabel62.setText("Viernes");

        jLabel72.setText("Sabado");

        jLabel82.setText("Domingo");

        jlun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlunActionPerformed(evt);
            }
        });

        jjue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjueActionPerformed(evt);
            }
        });

        jButton133.setText("Agregar");
        jButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton133ActionPerformed(evt);
            }
        });

        jButton212.setText("Regresar");
        jButton212.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton212ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel82)
                                    .addComponent(jLabel52))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jsab, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jvier)
                                    .addComponent(jdom)
                                    .addComponent(jjue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel22))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmier, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jlun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(jmar, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton212)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jButton133))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel113)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel113)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jlun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jmier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jjue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jvier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jsab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(jdom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton133)
                    .addComponent(jButton212))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jjueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjueActionPerformed

    private void jButton133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton133ActionPerformed
     agregarViaje();                                         
   
    }//GEN-LAST:event_jButton133ActionPerformed

    private void jButton212ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton212ActionPerformed
   Viaje v = new Viaje ();
    v.pack();
    v.setLocationRelativeTo(null);
    v.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton212ActionPerformed

    private void jlunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton212;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JTextField jdom;
    private javax.swing.JTextField jjue;
    private javax.swing.JTextField jlun;
    private javax.swing.JTextField jmar;
    private javax.swing.JTextField jmier;
    private javax.swing.JTextField jsab;
    private javax.swing.JTextField jvier;
    // End of variables declaration//GEN-END:variables
}
