/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginandsignup;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author sauls
 */
public class AgreAuto extends javax.swing.JFrame {

    /**
     * Creates new form AgreAuto
     */
    public AgreAuto() {
        initComponents();
        registrarAutobus();
        limpiarCampos();
        
        
    }
    private void registrarAutobus() {
    String placas    = jplacas.getText();
    String modelo    = jmodelo.getText();
    String capacidad = jcapacidad.getText();

    if (placas.isEmpty() || modelo.isEmpty() || capacidad.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String url = "jdbc:mysql://localhost:3307/registro";
    String usr = "root";
    String pwd = "";

    String sql = "INSERT INTO informacion (placas, modelo, capacidad) VALUES (?, ?, ?)";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection(url, usr, pwd);
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, placas);
            ps.setString(2, modelo);
            ps.setInt(3, Integer.parseInt(capacidad));  // Asegúrate de que solo números

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Autobús registrado correctamente.");
            limpiarCampos(); // limpia después del registro
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero.", "Error de formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar autobús:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
   private void limpiarCampos(){
    jplacas.setText("");
    jmodelo.setText("");
    jcapacidad.setText("");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabeqwe = new javax.swing.JLabel();
        jLabwq = new javax.swing.JLabel();
        jLabasd = new javax.swing.JLabel();
        jplacas = new javax.swing.JTextField();
        jmodelo = new javax.swing.JTextField();
        jcapacidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonaa = new javax.swing.JButton();

        jLabel1.setText("agregar autobus");

        jLabeqwe.setText("placa");

        jLabwq.setText("modelo");

        jLabasd.setText("capacidad");

        jplacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jplacasActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonaa.setText("Regresar");
        jButtonaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabwq)
                    .addComponent(jLabasd)
                    .addComponent(jLabeqwe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jplacas)
                    .addComponent(jcapacidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jplacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeqwe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabwq)
                    .addComponent(jmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabasd)
                    .addComponent(jcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonaa))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaaActionPerformed
       Informacion vas = new Informacion();
    vas.pack();
    vas.setLocationRelativeTo(null);
    vas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonaaActionPerformed

    private void jplacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jplacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jplacasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarAutobus();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonaa;
    private javax.swing.JLabel jLabasd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeqwe;
    private javax.swing.JLabel jLabwq;
    private javax.swing.JTextField jcapacidad;
    private javax.swing.JTextField jmodelo;
    private javax.swing.JTextField jplacas;
    // End of variables declaration//GEN-END:variables
}
