/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginandsignup;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sauls
 */
public class Agrpass extends javax.swing.JFrame {

    /**
     * Creates new form Agrpass
     */
    public Agrpass() {
        initComponents();
        limpiarCampos();
    }
    private void limpiarCampos() {
    jTexnom.setText("");
    jTexape1.setText("");
    jTexape2.setText("");
    jTexdni.setText("");
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTexnom = new javax.swing.JTextField();
        jTexape1 = new javax.swing.JTextField();
        jTexape2 = new javax.swing.JTextField();
        jTexdni = new javax.swing.JTextField();

        jLabel1.setText("agregar pasajeros ");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("nombre");

        jLabel3.setText("apellido_p");

        jLabel4.setText("apellido_m");

        jLabel5.setText("dni");

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTexnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexnomActionPerformed(evt);
            }
        });

        jTexape1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexape1ActionPerformed(evt);
            }
        });

        jTexdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexdniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(70, 70, 70)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTexnom)
                                            .addComponent(jTexape1)
                                            .addComponent(jTexape2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                                    .addComponent(jTexdni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTexnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexape2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTexnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexnomActionPerformed

    private void jTexape1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexape1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexape1ActionPerformed

    private void jTexdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexdniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nombre     = jTexnom.getText().trim();
    String apellidoP  = jTexape1.getText().trim();
    String apellidoM  = jTexape2.getText().trim();
    String dni        = jTexdni.getText().trim();

    if (nombre.isEmpty() || apellidoP.isEmpty() ||
        apellidoM.isEmpty() || dni.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Todos los campos son obligatorios",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // 2) Parámetros de conexión
    String url  = "jdbc:mysql://localhost:3307/registro";
    String usr  = "root";
    String pwd  = "";
    String sql  = "INSERT INTO pasajeros (nombre, apellido_p, apellido_m, dni) VALUES (?, ?, ?, ?)";

    // 3) Ejecutar el INSERT
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection(url, usr, pwd);
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, nombre);
            pst.setString(2, apellidoP);
            pst.setString(3, apellidoM);
            pst.setString(4, dni);

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(
                    this,
                    "Pasajero registrado con éxito",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
                // 4) Limpia los campos
                jTexnom.setText("");
                jTexape1.setText("");
                jTexape2.setText("");
                jTexdni.setText("");
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el pasajero",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    } catch (ClassNotFoundException cnf) {
        JOptionPane.showMessageDialog(
            this,
            "Falta el driver de MySQL:\n" + cnf.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (SQLException sqle) {
        JOptionPane.showMessageDialog(
            this,
            "Error en la base de datos:\n" + sqle.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Pasajero  next5 = new Pasajero();
    next5.pack();
    next5.setLocationRelativeTo(null);
    next5.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTexape1;
    private javax.swing.JTextField jTexape2;
    private javax.swing.JTextField jTexdni;
    private javax.swing.JTextField jTexnom;
    // End of variables declaration//GEN-END:variables

   
}
